openapi: 3.0.0
info:
  title: Web API Skeleton
  description: Skeleton for Dropwizard Web APIs
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
servers:
  - url: http://localhost/api/v0

paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          description: Object containing information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    pretty:
      name: pretty
      in: query
      schema:
        type: boolean
      required: false
      description: If true, JSON response will be pretty-printed
  schemas:
    Info:
      properties:
        name:
          type: string
          description: Name of the API.
        time:
          type: string
          description: Build time in ISO 8601 format.
        unixTime:
          type: integer
          description: Build time as milliseconds since the unix epoch.
        commit:
          type: string
          description: Git commit hash of the revision which was built.
        documentation:
          type: string
          description: Filename of the OpenAPI specification for the API.
    Error:
      properties:
        status:
          type: integer
          description: HTTP status code.
        developerMessage:
          type: string
          description: An error string aimed at developers.
        userMessage:
          type: string
          description: An error string aimed at end users.
        code:
          type: integer
          description: Error code.
        details:
          type: string
          description: A link to further information about the error.
